version: "3"
services:
  postgres:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:latest
    ports:
      - "9091:9091"
      - "9000:9000"
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9091"